### ISSUE TITLE
タブの数が20個以上になるとE541と表示される

### ISSUE THREAD

**Issue by itchyny** [yami-beta/vim-responsive-tabline#1]
重箱の隅をつつくようなissueで申し訳ないのですが、こういう現象があるということをお伝えしておきます。
(個人用途だとそんなに開くことはないから対応しない、でもいいと思います)

ありそうでなかった、おもしろい発想のプラグインだと思います。

**Comment by yami-beta** [comment]
`E541` の件確認いたしました。
とりあえず README に既知のバグとして記載しておきます。
ご報告ありがとうございます。
